
worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       9090;
        server_name  localhost;

       location / {
            proxy_pass http://192.168.53.157:3000;
       }

       location /api {
            proxy_pass http://ccp-util-man.ukwest.cloudapp.azure.com/api;
       }
    }

# //    
    server {
       listen       9999;
       server_name  localhost  alias  another.alias;

       location / {
            proxy_pass https://icy-hill-0f9985803.3.azurestaticapps.net;
       }

       location /user {
            proxy_pass https://dev.mployr.com;
       }

       location /job {
            proxy_pass https://dev.mployr.com;
       }

      location /message {
               proxy_pass https://dev.mployr.com;
          }

          location /meeting-timesheet {
               proxy_pass https://dev.mployr.com;
          }
    }
}